name: sTablist
author: Jul1an_K
version: ${project.version}
softDepend: [PlaceholderAPI, Vault]
main: me.jul1an_k.tablist.bukkit.Tablist


commands:
  settab:
    description: Set Header or Footer 
    usage: /<command>
  update:
    description: Update
    usage: /<command>
  stabinfo:
    description: Info
    usage: /<command>
  stablist:
    description: Broadcast and more
    usage: /<command>
    aliases: [stl, sTlist, sTabl, sT]
    
permissions:
    sTablist.*:
        description: All Permissions of sTablist
        children:
            sTablist.reload: true
            sTablist.settab: true
            sTablist.update: true
            sTablist.broadcast: true
            sTablist.msg: true
            sTablist.setprefix: true
            sTablist.setsuffix: true
            sTablist.del: true
            sTablist.regenconfig: true
            sTablist.copyfrompermissionsystem: true
            sTablist.help: true
